$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: ci-cd-pipeline-demo
experiment_name: ci-cd-pipeline-demo

settings:
  default_compute: azureml:cpu-cluster

inputs:
  pipeline_raw_data:
    type: uri_file
    path: azureml://subscriptions/62a864c9-87b7-42dc-b40c-c74b95d54368/resourcegroups/mlops/workspaces/azure-ml/datastores/workspaceblobstore/paths/UI/2025-11-14_212359_UTC/credit.csv

jobs:
  prep_data_job:
    type: command
    component: file:./components/data_prep.yml
    inputs:
      raw_data: ${{parent.inputs.pipeline_raw_data}}
    outputs:
      prep_data_dir:

  train_model_job:
    type: command
    component: file:./components/train_model.yml
    inputs:
      prep_data_dir: ${{parent.jobs.prep_data_job.outputs.prep_data_dir}}
    outputs:
      model_dir: 

  register_model_job:
    type: command
    component: file:./components/register_model.yml
    inputs:
      model_dir: ${{parent.jobs.train_model_job.outputs.model_dir}}
      model_name: "credit-risk-model"